import { readFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join, relative, resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, "..");
const botRoot = join(root, "ShiggyBot");
const outFile = join(root, "src", "data", "csFiles.ts");

function findCsFiles(dir: string, maxDepth = 3, depth = 0): string[] {
  if (depth > maxDepth) return [];
  const results: string[] = [];
  try {
    for (const entry of readdirSync(dir)) {
      const fullPath = join(dir, entry);
      if (
        entry === "obj" ||
        entry === "bin" ||
        entry === "node_modules" ||
        entry === "publish" ||
        entry === "Website"
      )
        continue;
      if (statSync(fullPath).isDirectory()) {
        results.push(...findCsFiles(fullPath, maxDepth, depth + 1));
      } else if (entry.endsWith(".cs")) {
        results.push(fullPath);
      }
    }
  } catch {}
  return results;
}

const files = findCsFiles(botRoot);
const entries = files.map((f) => {
  const rel = relative(botRoot, f);
  const code = readFileSync(f, "utf-8");
  return { path: rel, code };
});

const code = `// auto-generated by scripts/generate-cs-index.ts
export interface CsFile {
  path: string;
  code: string;
}

export const csFiles: CsFile[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(outFile, code);
console.log(`Generated ${outFile} with ${entries.length} files`);
